### ISSUE TITLE
Project load failing in Visual Studio 2017

### ISSUE THREAD

**Issue by fcbertoldi** [Polytonic/Glitter#46] opened 2018-05-29 17:18 UTC
When building the project with Visual Studio 2017 I had the following error (translated, original message was in portuguese):

```
src\Glitter\Build\vc15\Glitter.vcxproj : error  : unable to load project with duplicated itens: src\Glitter\CMakeLists.txt is included as 'CustomBuild' and 'None' types.
```

Removing `${PROJECT_CONFIGS}` from the list of sources in `add_executable` solves the problem.

PC settings:
Windows 10 version 1803
CMake version: 3.11.0.
Visual Studio 2017 version 15.7.2

**Comment by Polytonic** [comment] 2018-05-31 06:52
Hmm. I can't recall having tried with VS2017 yet. Are you using Community Edition?

This week is a bit of a mess for me, but I can try to take a look at this over the weekend. 😬

**Comment by fcbertoldi** [comment] 2018-06-01 13:37
That's fine, I just wanted to report the problem, no need to hurry. 🙂

The problem occurred in both VS2013 and VS2017 Professional Edition.

In my home PC with VS2017 Community Edition I applied the fix without first reproducing the problem, and it worked.

**Comment by Polytonic** [comment] 2018-06-05 08:07
Hm, I wasn't able to reproduce this locally. I did some research online -- looks like this is actually a [CMake bug](https://gitlab.kitware.com/cmake/cmake/issues/17828). If it's not too much trouble, would you mind updating your cmake installation and trying again? 

For what it's worth, `${PROJECT_CONFIGS}` is only needed if you want `CMakeLists.txt` and `Readme.md` and such to show in the Solution Explorer. If you don't need to modify those much, your workaround is probably fine. 🙂

**Comment by Polytonic** [comment] 2018-08-08 02:33
Closing for now, per my previous comment, and there has not been an update in a while. Feel free to reopen if this comes up again. 🙂

**Closed by Polytonic** 2018-08-08 02:33 UTC
